### ISSUE TITLE
Better contrast between selected item and the rest in the list

### ISSUE THREAD

**Issue by spydon** [bluefireteam/dashbook#105]
# What could be improved
Currently it is quite hard to see which example that has been chosen:

![image](https://github.com/flame-engine/flame/assets/744771/2f773f56-3ff5-4154-9cb0-bb1f33e83b01)

It would be good to have a better contrast between the two texts.
Maybe through color, opacity, or underlining (or a mix of them).

# Why should this be improved
To make it easier for the users of the example site to navigate.

# More information
https://examples.flame-engine.org

**Comment by yoonnikuu** [comment]
Let me try! ;)

**Comment by immadisairaj** [comment]
If this is still free, I can work on it. I am thinking to change the text colour of unselected to a lighter variant something like `Theme.of(context).hintColor`.

**Comment by immadisairaj** [comment]
This is linked to flame-engine/flame#2790 (just commenting so the issues are linked)

**Comment by spydon** [comment]
> If this is still free, I can work on it. I am thinking to change the text colour of unselected to a lighter variant something like `Theme.of(context).hintColor`.

Great, I'll assign you to it!
