### ISSUE TITLE
Remove spaces / replace them with underscore for the links

### ISSUE THREAD

**Issue by immadisairaj** [bluefireteam/dashbook#110]
As per https://github.com/flame-engine/flame/issues/2895#issuecomment-1914889238, it is good that we have links generated with `_` instead of ` ` (which turns out as `%20`).

Stories of ('Collision Detection') - Story ('Collidable AnimationComponent')

Current Link example: 
Collision%20Detection_Collidable%20AnimationComponent

Expected Link example: 
Collision_Detection_Collidable_AnimationComponent

**Comment by spydon** [comment]
Should I assign you to this @immadisairaj?

**Comment by immadisairaj** [comment]
Let it be open for others (for time being). But, there's a high chance I might work on it and send a PR (I will add inform here if I start working on it).

**Comment by immadisairaj** [comment]
Please assign me this issue @spydon.

I found the issue and fixed it already 😅🙂
