### ISSUE TITLE
Ability to set viewport directly from canvas screen.

### ISSUE THREAD

**Issue by chimon2000** [bluefireteam/dashbook#30]
On the canvas/preview screen in storybook, users can select the viewport size.  It would be nice to have this feature in dashbook.  Here's an [example](https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-backgrounds--overridden):

<img width="740" alt="Screen Shot 2021-01-21 at 11 36 57 PM" src="https://user-images.githubusercontent.com/6907797/105447134-9eb19580-5c41-11eb-838e-7f6e0204ccb3.png">

The options provided are:

- Reset (default)
- Small mobile
- Large mobile
- Tablet

Selecting a viewport shrinks the canvas viewport size.  I think this helps usability because the developer no longer has to shrink the browser (if they are using chrome) or open devtools.

**Comment by erickzanardo** [comment]
This is a great idea, and seems fairly easy to implement, gonna try to make it when I get some free time

**Comment by ogustavobelo** [comment]
Just to understand better... We already have a device preview feature. Should this issue be a new button with similar functionality?

**Comment by spydon** [comment]
I think this issue is already done (and should be closed) in the device preview feature that you mention:
![image](https://user-images.githubusercontent.com/744771/147946385-cd12f663-0134-4ff9-9023-adce5404e89d.png)

**Comment by erickzanardo** [comment]
We I think the device preview is missing the ability to add a custom viewport, right now we can only select from a predefined list

**Comment by spydon** [comment]
> We I think the device preview is missing the ability to add a custom viewport, right now we can only select from a predefined list

This issue only mentions a predefined list though?

**Comment by erickzanardo** [comment]
We could close this if we open a new one then, and track the custom sizes there. Wdyt?

**Comment by spydon** [comment]
> We could close this if we open a new one then, and track the custom sizes there. Wdyt?

Sounds good! And say that #64 fixed this.
