### ISSUE TITLE
[Bug] Crash on flutter run (caused by flutter_colorpicker >= 0.5.0)

### ISSUE THREAD

**Issue by Kusken** [bluefireteam/dashbook#60]
**Platfrom:** Linux
**Flutter Version**: (Channel stable, 2.2.1)
**Device**: Android Emulator (Pixel 3a)

**Reproduction steps**:
1. Clone this repo
2. run `cd **/dashbook/example`
3. run `flutter run --debug`

**Process exits and the following with Error message is shown:** 
```
/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.5.0/lib/src/hsv_picker.dart:730:43:
 Error: The parameter 'event' of the method 'AlwaysWinPanGestureRecognizer.addAllowedPointer' has type 
 'PointerDownEvent', which does not match the corresponding type, 'PointerEvent', in the overridden method, 
 'DragGestureRecognizer.addAllowedPointer'.
```

**Description:**
The issue is caused by color picker >= 0.5.0.
[There is currently an open issue](https://github.com/mchome/flutter_colorpicker/issues/49) in the color picker repo.

**Fix**:
Downgrade flutter_colorpicker to 0.4.0

**Local fix**:
If you run in to this problem before this issue has been resolved in this repos package you can temporarily solve it buy adding an dependency override caluse to you pubspec.yaml, like this:

```
dependency_overrides:
  flutter_colorpicker: ^0.4.0
```

**Comment by Kusken** [comment]
Was thinking about making a pull-request but since 0.4.0 doesn't seem to work with **flutter version 2.5.0** the better alternative is just to override the dependency for flutter_colorpicker if you cannot upgrade flutter.

**Comment by erickzanardo** [comment]
This was fixed on the previous version.
