### ISSUE TITLE
Upgrading dependencies

### ISSUE THREAD

**Issue by adigladi** [bluefireteam/dashbook#76]
Right now there are some dependencies that are not updated, which is blocking us from upgrading the freezed-package to the stable version by depending on dashbook. Is it possible to fix this? `device_frame` in particular:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/35582133/159498473-15627b9d-e5a2-4556-b354-72921ac6daed.png">

**Comment by erickzanardo** [comment]
Fixed on 0.1.7, thanks for the PR!
