### ISSUE TITLE
colorProperty is closing the page in Flutter Web

### ISSUE THREAD

**Issue by emersonsiega** [bluefireteam/dashbook#84]
I'm trying to use `colorProperty` to let users change some widgets color.
The color picker is opened correctly with default color, but when I try to change the color and confirm in "Got it" button, the background page is closed instead of color picker modal.

This is how I'm using the `colorProperty`:
```dart
final bool customize = dc.boolProperty('Customize colors', false);
final Color backgroundColor = dc.colorProperty(
      'backgroundColor',
      Colors.grey,
      visibilityControlProperty: ControlProperty('Customize colors', true),
);
```

This is what's happening:
![Screen Recording 2022-06-18 at 01 45 15 PM](https://user-images.githubusercontent.com/2227499/174448473-b2cbd646-190f-43d0-a60e-829f0528e876.gif)

**Comment by Dohmanlechx** [comment]
Same issue here. I believe this [line](https://github.com/bluefireteam/dashbook/blob/main/lib/src/widgets/property_widgets/color_property.dart#L46) is the culprit. 😄

**Comment by spydon** [comment]
Anyone wants to send a PR with a fix? 😊

**Comment by Dohmanlechx** [comment]
> Anyone wants to send a PR with a fix? 😊

https://github.com/bluefireteam/dashbook/pull/102

**Comment by spydon** [comment]
0.1.13 released with the fix!
