### ISSUE TITLE
Theming of Dashbook breaks when adding multiple instances

### ISSUE THREAD

**Issue by renefloor** [bluefireteam/dashbook#86]
Dashbook breaks when you add multiple instances of it. I'd like to do this because we are building a design system for multiple brands at the same time and I'd like to be able to switch between them.

The widget just floats away to the right and nothing comes back for it.

https://user-images.githubusercontent.com/15101411/179258847-4020eb03-58e7-4872-bf8e-6b79da0f61dd.mov

A made a gist with a small example (from the video): https://gist.github.com/renefloor/66c4d5011f6ab8c899ce0f36acec1512

**Comment by erickzanardo** [comment]
Fixed by #87
