### ISSUE TITLE
Move device properties to side panel instead of pop-up

### ISSUE THREAD

**Issue by lohnn** [bluefireteam/dashbook#96]
Adding interactive side panel device info settings would make it possible for users to quickly try out different device settings.

My idea is something akin to this:
![image](https://user-images.githubusercontent.com/960157/202815942-0b26d1ba-0652-49d2-b1bf-caa0326d0dcb.png)

If you agree that this is a good idea, you can assign me as I'm taking a stab at this 👍

**Comment by erickzanardo** [comment]
Hey 🖖

I am not sure I fully understand, is there any more differences other than just changing the modal to a side panel?

**Comment by lohnn** [comment]
Well, some small GUI tweaks to tailor it to side panel of course. I'd propose moving the device orientation and "show device frame" buttons to the side panel to keep them with the device settings.
But mainly making it updating the device settings in real time as you update the values in the side panel. Like sliding the text scale factor updates the text in real time in the preview. Like such:

https://user-images.githubusercontent.com/960157/202857722-cd6f6436-1761-4cfc-a0c7-091d3379709b.mov

**Comment by erickzanardo** [comment]
I like the idea, the only addition that I would suggest is to add a checkbox with the label use custom device, that would be unchecked by default.

Once it is checked, then the custom device fields would appear, wdyt?

**Comment by lohnn** [comment]
Finally had some time to spare. How would this be as a first version?

https://user-images.githubusercontent.com/960157/206706261-852e1580-4c46-40fc-90c4-9119dd268928.mov

**Comment by erickzanardo** [comment]
That LGTM! Awesome

**Comment by lohnn** [comment]
Then I'll make sure the tests are running properly and make a PR :)

**Comment by lohnn** [comment]
Then there is a PR to look at ;) #98

**Comment by erickzanardo** [comment]
Solved by #98 released on `0.1.12`
